name: Build Marp Slides

on:
  push:
    branches: [main]
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert Markdown to HTML
        uses: KoharaKazuya/marp-cli-action@v3
        with:
          args: presentation_portfolio.md --html --output dist/index.html

      # This step must be indented just like the steps above and below it
      - name: Check output folder
        run: ls -R dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
